### PR TITLE
Added tool selection from config file. Added parametrized SpindelHolderA...

### PR DESCRIPTION
**Pull request by quikshot**
...ttach option for Z_Carriage.

Many spindles come with an alluminium holder which is very solid and hold and dissipates the heat very well. This change allows you to print a part to attach to this spindle holder, making a very solid Z_Carriage.

To do this, just select tool=spindle_holder instead of tool=dremel and z_carriage will be like the one in the picture. Parameters are shown in the pic.

### CODE REVIEW

**Comment by D-Byte** [comment]
Looks good, nice work.

**Comment by carlosgs** [comment]
Awesome, thanks!

**Comment by quikshot** [comment]
Thanks for merging!
Hope it helps someone.

**Comment by carlosgs** [comment]
Oh and very neat idea to provide an image with the overlayed variable names :)

**Pull request merged**
